services:
  - type: web
    name: instaXformer
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
